name: flutter_catalog
description: A new Flutter project.

dependencies:

  cloud_firestore:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sticky_headers:

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_maps_flutter:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
  # image assets are referred to in Dart using the names listed here.
  # Note that the actual image files may reside in subdirs under assets
  #
  # zoom_menu
    - assets/alogo_claire_white.png
    - assets/alogo_nina_white.png
    - assets/alogo_rachel_white.png
    - assets/simpsons_homer_donut.png
    - assets/simpsons_snowball_v.png
    - assets/simpsons_hellfish.png
    - assets/dark_grunge_bk.jpg
    - assets/wood_bk.jpg
    - assets/donut-bk.png
    - assets/hellfish-bk.png
    - assets/snowball-bk.png
    # blurry_artist
    - assets/avatar.png
    - assets/backdrop.png
    - assets/video1_thumb.png
    - assets/video2_thumb.png
    - assets/video3_thumb.png
    - assets/video4_thumb.png

  fonts:
  # font assets are referred to in Dart using the family names shown here.
  # Note that the actual font files must reside in the path specified here
     - family: mermaid
       fonts:
         - asset: assets/zoom_menu/Mermaid1001.ttf
     - family: bebas-neue
       fonts:
         - asset: assets/zoom_menu/BebasNeue-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
